### ISSUE TITLE
Put in policies info from the old page to replace placeholder info

### ISSUE THREAD

**Issue by maryjom** [w3c/wai-policies-prototype#133]

**Comment by yatil** [comment]
We need to make sure that the entries from the old page are still valid, I think I’d be hesitant to start with a new page but with really, really outdated info.

**Comment by maryjom** [comment]
@yatil I'm only going to put in there if links are working, etc. If nothing exists today, like for Denmark, I'm going to remove that country.  If you have any info or clues to get info for any of the European countries let me know.

**Comment by slhenry** [comment]
I will reach out to known people and ask them to submit data, e.g,. Helle can probably give us Denmark.

**Comment by slhenry** [comment]
I sent e-mail to Helle (off list because I didn't want to spread her personal email address).

I sent https://lists.w3.org/Archives/Public/wai-eo-editors/2017May/0004.html

I'll send some more when I can.

And, once we're ready, we can do a call to WAI IG for more. ***but*** let's **wait** until we have our processes in place for reviewing, approving, and posting submitted info.
