### ISSUE TITLE
meta data for social media etc.

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-policies-prototype#243]
Here are [options for thumbnail images](https://lists.w3.org/Archives/Public/wai-eo-editors/2017Jun/0003.html)

**Comment by yatil** [comment]
I did upload the pages.
I did not receive any metadata for social media or otherwise, so I did not include it. The proposed thumbnail images do not meet the requirements of social networks and are very blurry and not welcoming.

For the previous policies document we had the following metadata (thanks to @lakeen):

* Title: Policies Relating to Web Accessibility (**Now: Web Accessibility Laws and Policies**)
* URL: http://www.w3.org/WAI/Policy/	
* Description: This resource provides a list of existing laws and policies regarding Web accessibility.	
* Tags: Australia, Canada, Denmark, European Union, Finland, France, Germany, Hong Kong, India, Ireland, Israel, Italy, Japan, New Zealand, Portugal, Spain, Switzerland, United Kingdom, United States of America, web accessibility policy

We need all of the above and, for [maximum social network compatibility](https://sproutsocial.com/insights/social-media-image-sizes-guide/):
* [ ] A 1200x627 pixel large image that represents the content.
  * I made a [proposal](https://lists.w3.org/Archives/Public/wai-eo-editors/2017Jun/att-0005/01-part), which is not sufficient.
  * @iamjolly thought about using an image with various flags as an eye catcher, an idea which I like. (for example this: https://upload.wikimedia.org/wikipedia/commons/1/1b/International-flag.jpg)

**Comment by yatil** [comment]
Talked to @slhenry,

* We don’t want to list all the countries as tags but use the types (policies, laws, …) 
* use this sentence from the intro for the description: “Lists governmental policies relating to web accessibility in countries and regions around the world.”
* For the sharing image, I will make a screenshot of the page. We both agreed that we need a template for those images but did not want to run it by the group first but announce it :-)
