### ISSUE TITLE
Level of information per country is inconsistent

### ISSUE THREAD

**Issue by yatil** [w3c/wai-policies-prototype#295]
_From @maryjom on August 19, 2016 23:6_

The structure & level of information for each country is inconsistent. There are several unneeded and non-working references in the additional information.

_Copied from original issue: w3c/wai-policieslist#4_

**Comment by maryjom** [comment]
@yatil @iamjolly This is by design now if we are allowing the minimum information per country to be only the policy/standard name with a link, and the country it belongs to.  The thing we need to look into is how to represent any missing data on the country page and on the summary page, and fix the sorting algorithms, if needed, to handle that.

**Comment by yatil** [comment]
Yes, I think that’s something we need to look at. I think we need a clear link on the country page when we have little information. If we’re missing a certain info we might write “unknown” as a value to underline that this is not something that is not applicable but something we don’t know.

**Comment by iamjolly** [comment]
This is no longer an issue due to our minimum requirements for inclusion in the resource.
