### ISSUE TITLE
[ED] Country pages out of date

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-policies-prototype#321]
We may want to push this off to the broader site-wide issue of how to address old pages that we're not updating.

* https://w3c.github.io/wai-policies-prototype/policies/australia/ links up top to https://www.w3.org/WAI/Policy/CA-Provinces.html which hasn't been updated since 2002.
* https://w3c.github.io/wai-policies-prototype/policies/canada/ links up top to https://www.w3.org/WAI/Policy/AU-States.html which hasn't been updated since 2006.
* https://w3c.github.io/wai-policies-prototype/policies/united-states/ links up top to https://www.w3.org/WAI/Policy/USA-States.html which hasn't been updated since 2003.

While we would like to update those some time, it looks like it will be quite a while before we do. 

Options off the top of my head:
1. Delete the links because the info is so old as to not be useful to some people.
CON: Some people would like the info, even though old.
2. Leave the link because some of it will be useful to some people.
2.a. Add to the link "(Last updated 200X)" so people know it's old before going there.
CON: People might think the other info on this page is that old.
3. Leave as is.
PRO: They can go there if they want, and once they get there, they'll see that it's old.

OK, I guess I talked myself into leaving as it. :-)

In any case, @bakkenb and @sharronrush will want to note that updating those sub-pages should be on EOWG Future Work list. :-)

**Comment by bakkenb** [comment]
Hummm.  Good Question.

Also not that at the top of all the "old" pages there is a link back to the main policies page, which currently goes to the old policy page. Will that automatically change when the new site is in place, or will be have to hit those URLs for updates too?

To help answer your original question above, what information is on these old pages that people would want? And this is where I am admitting that I have not dug into the links to fully understand. For example, on the Canada page, there is just Ontario legislation. Rather than link to that page, if the legislation is still active can we not just get that added to the new resource? I may be missing something about the content that is on these other older pages though. Just some thoughts.

**Comment by slhenry** [comment]
Yes, links will work when on new site.

/me thinks can of worms, and lets address them all later.
