### ISSUE TITLE
How do we handle showing text and links are in another language?

### ISSUE THREAD

**Issue by maryjom** [w3c/wai-policies-prototype#35]
For example, in France the title of their standard is in French. How do we mark up that language change in the prototype code?  

In addition, the links will go to a French language page. Should there be some indication that the link takes you to a French-only page?

**Comment by yatil** [comment]
Eric to work on this issue and make sure we can optionally have English and Original language title and attach the corresponding lang attributes.

**Comment by iamjolly** [comment]
Is this still something we feel is necessary for the Policies Launch? Or, is this more of a Post-Launch Enhancement?

We can use the [`hreflang` attribute](https://www.w3.org/TR/html5/links.html#attr-hyperlink-hreflang) to advise of the language of the linked page/document. But, User Agents (browsers) may not do anything with that in terms of alerting the user. 

Should we (instead of or in addition to the `hreflang` attribute) provide a brief bit of informative text within the anchor text to have the language visible? An example of this might be: [Law N° 2005-102 Article 47 (French/Français)](#)

Other ideas are welcome.

**Comment by vuxcaleb** [comment]
I do not feel this is a show stopper before publishing but I agree with @iamjolly. W3 has a doc called [Indicating the language of a link destination](http://www.w3.org/International/questions/qa-link-lang)  which describes using `ahreflang` attr with a CSS snippet which displays the country code value as the display.

[Live Demo](http://www.w3.org/International/questions/qa-link-lang-data/sv)

**Comment by yatil** [comment]
From the meeting on May 5th:

RESOLUTION: Link text will be the English title of the external document The native language title will appear in unlinked parentheses. A note that links may go to other languages will be presented in the introductory text. The issue will be revisited after launch.

**Comment by slhenry** [comment]
Basic usability is that users should know what a link goes to. Users should not have to click a link to find out what language the document is in.

I feel pretty strongly that the link should be on the language of the document. That is, if the document is in non-English language, then the document title in that language should be the link.

(fyi, here's the [formatting we used before](https://www.w3.org/WAI/Policy/updates.html#formats) I do not feel strongly that we need to include [language] before links in that language.)

**Comment by maryjom** [comment]
@yatil One more case to take care of. See France. The title of the French standard in the standards.yaml file is French. Great job on the others though!
