### ISSUE TITLE
Summary table - scope column

### ISSUE THREAD

**Issue by AndrewArch** [w3c/wai-policies-prototype#5]
@maryjom suggested: need to add 'Scope' column per Andrew’s comment in 23/Sept meeting.

_me_: this column would reflect which sectors the 'policy' applies to, eg Govt only,

**Comment by bakkenb** [comment]
I see the scope column has been added to the [prototype](https://w3c.github.io/wai-policies-prototype/).

Some people mentioned that we want to be careful not to add too much data in the table so that it does not become overwhelming to use, sort, and consume. Not sure what columns should be kept or removed at this point. What do others think about this?

**Comment by sharronrush** [comment]
All seem useful and important to me except for the Wen Only question. I think that could go in supporting materials

**Comment by slhenry** [comment]
I'm one who wants to keep the table simple -- however, I can see the case for users wanting to filter &/or sort for this info -- so probably good to leave in the table.

**Comment by yatil** [comment]
We can show/hide certain columns of a table – which brings UI complexity (we can handle that), but it would also require us to find out which data to present by default and what columns we want to put into the table.

**Comment by slhenry** [comment]
/me thinks probably not worth the added complexity of show/hide columns - but don't feel strongly at this point (without seeing it)

**Comment by dboudreau** [comment]
I'd also want the table to be simpler. I'm not really of fan if showing/hiding columns, because all this interaction just makes it harder for someone who can't see the screen.

I would only keep the following columns:

- New/updated
- Country
- Law/legislation name
- Type
- Scope

The other pieces of information are relevant, but not critical, and could be made part of the details below.

**Comment by yatil** [comment]
+1 to simplify, I think @dboudreau’s suggestions sound great.

**Comment by AndrewArch** [comment]
@dboudreau it also makes it more complicated for someone who only sees part of the screen and someone who has difficulty with tabular structures

+1 to simplify :)

**Comment by iamjolly** [comment]
+1 to @dboudreau's suggestions to simplify table, possibly use filters instead to allow for @maryjom's use case for people finding what's enforced vs proposed, etc.

**Comment by yatil** [comment]
I could imagine a simple [x] Show details checkbox for the table, which would by default be unchecked.

**Comment by yatil** [comment]
Or put the table on another page.

**Comment by dboudreau** [comment]
Afer having discussed and heard @sharronrush and @maryjom's use case, I would be in favor of keeping "status' but the removing "Law/legislation" because it's likely a more granular level of information that's only relevant if you've already selected a country... in which case, that kind of information could be placed in the details underneath.

**Comment by slhenry** [comment]
Discussion in [10 Feb telecon](https://www.w3.org/2017/02/10-eo-minutes.html#item04)

**Comment by maryjom** [comment]
The policy name column needs to be added back in the table because now you've got countries listed multiple times and no information on why other than the type and scope fields which is meaningless.

**Comment by yatil** [comment]
@maryjom We can group the countries together, but I don’t think that would be really easy to digest – probably better to have the policy name in there imho.

**Comment by maryjom** [comment]
@yatil @AndrewArch  Thanks Andrew, that's what I meant.  The removal of the names of the laws from the table makes the whole thing meaningless. I think Robert was trying to implement the suggestion of Denis not realizing the law name is pretty critical to have in there.

**Comment by iamjolly** [comment]
nothing left to do here
