### ISSUE TITLE
All on one page, or countries separate?

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-policies-prototype#56]
[I didn't see an issue on this point. Sorry if I missed it.]

We've talked about the default being one starting page, and then each country on it's on page. (*and* also an option to get it all on one page.)
(@sharronrush - do you happen to have pointer to relevant minutes???)

This has implications on the current prototype -- e.g., are the Filtering options within the Table section, or before it?

**Comment by bakkenb** [comment]
Good question. I think to know best it would be good to do some user testing on a more complete draft prototype. After people view what is in the table, find out what they would expect to see below the table, and then on a separate country or state/province page. 

- "What did you expect to see when you clicked on the country name in the table?"
- "What did you expect to see listed under each country in the bottom part of the Main page?"
- "What did you expect to see when you when to the country's main page?"
- "Is the data in the right place? Should any of the data be moved around from the main page to the individual page or vise versa so it is easier to find?"
- "Was it intuitive when a link was going to more information on the resource or leading you out of the resource to the actual policy or law documentation?"
- etc...

In the user testing, it would be good to know that we have some people who really do look at this type of data often.

**Comment by bakkenb** [comment]
Personally, I would prefer seeing the table only on the landing page (along with being able to sort or filter), and then the name of the country in the table would link directly to the country page with the rest of the details.

To me it is confusing to have *some more* of the country details down below the table, as well as "even more" details on an individual country page. I start asking myself, is this information also over in these other places or not? What do I need to remember from this list because it may not be repeated on the individual page? It is just easier to have the table and then click the country name in the table to get to the country page with ALL the details for that country. (I am open to opinions though because I know there are different use cases to consider)

**Comment by slhenry** [comment]
I continue to support the default of only the table on the main page, and the country details on separate pages.

In rare cases, someone might want to see or even print out all the data. Therefore, I continue to support providing option to get all of the data one one page -- e.g.,  [Understanding](https://www.w3.org/TR/UNDERSTANDING-WCAG20/) has _Single file version_ -- though this doesn't need to be prominent.

**Comment by slhenry** [comment]
I also suggest using the full width of the page for the table. That will help those using small screens &/or large text.

Since we won't have the countries on this main page, we don't need a nav column on the left.

**Comment by sharronrush** [comment]
Strongly support displaying only the table on the main page, and the country details on separate pages.

**Comment by nrhsinclair** [comment]
To me the list below the table looks like a second useful way of presenting the information. I like seeing all of the laws/legislation listed together under the country name. It could be a useful way for individuals to more easily reuse the information if they planned to copy and paste it into a report for example.

**Comment by haltersweb** [comment]
I don't mind the table but its blind should start out closed.  This is a cognitive issue.

As a person with severe ADD I found my brain scrambled while looking at this page.  I spent about 5 minutes trying to figure out what this page was about (no joke) because my eyes couldn't figure out where to land.

I need a simple UX experience with low content to understand the page.  Then I will unfurl what I decide to drill into.  

In the same vein the By country section should also be a closed blind with the option to open upon reviewing the page.

Thanks :-)

**Comment by iamjolly** [comment]
@nrhsinclair and @haltersweb - Thank you for that feedback. We are going to go with making the MVP of the new policies page display the summary table (with filtering capability) and link to separate country pages with detailed policy information on them. 

We want to perform some usability testing at AccessU 2017 (and possibly shortly after) on this MVP to determine what works well for folks and what may be problematic. Having your comments will help inform our usability tasks and ensure we uncover any problems with complexity and understandability in the user interface. Any changes that are needed will come in a post-MVP release.
