### ISSUE TITLE
'new'/'updated' indicator

### ISSUE THREAD

**Issue by AndrewArch** [w3c/wai-policies-prototype#7]
@maryjom said: 
- I still like the idea of an update icon here. It can be programmatically added [o each entry] if the last updated date is less than 3 months from the current date and is not too attention grabbing.  Looking at actual dates cause more cognitive power, and an icon makes it easier to skim.
- Also, not sure how long we’d want a “new” or “update” icon to appear.  Maybe only for a month or so. We should have a regular time to go quickly update that info on the page so it doesn’t get stale.
- Do we want a description of what changed since the last update to this country’s info.?

**Comment by yatil** [comment]
* +1 to flag new
* +1 for a specified time
* I think we might also want “upcoming” for laws that will come into power in, say, like three months
* Do we want to keep superseded laws (for archival purposes, probably deeply buried, not prominent)

**Comment by bakkenb** [comment]
+1 for "new" and "updated" flag. Vote for 3 months and then the flags expire.

**Comment by sharronrush** [comment]
Archived history of laws that have been superseded seem necessary to me, but if others think important, could create a "History" section in supporting material outside of the table.

**Comment by slhenry** [comment]
I'm wondering about the usability and usefulness -- particularly, how many users would find the update icon useful. I'm concerned that it will be too distracting (especially for those of us whose attention gets sucked in by graphics :).

Also, we would need to explain that the icon indicates when info on this page was updated, not when the policy itself was updated. So that would require more text, and little more cognitive load, and potential for confusion.

Two other ideas:
* What about making that optional functionality, e.g., highlight changes from the last 1 month, 3 months, 6 months. I think that would be useful... although, then adds a bit of complexity, which may not be worth it.
* We talked about having an update notification mailing list. Would that take care of it? We can say on this page, if you want to see what has been updated, here's a link to the archive. Right now, this is my preference, to limit visual clutter on this page.

**Comment by sharronrush** [comment]
@slhenry well you know me an icons. I find few of them useful so I always defer to those who want them. I think the notification alert is great and am indifferent to the 'new' flag

**Comment by slhenry** [comment]
**History:**
I think this is low priority. Would be nice to have, but not worth dealing with it now. (Agree with Sharron, it would need to be clearly indicated.)

**Comment by yatil** [comment]
Question is what we think as an “icon”. for me we could just mark it with “(new)” or “(updated)” – I think it builds trust that the information is current and updated.

I don’t feel strongly.

**Comment by yatil** [comment]
(The implementation is trivial, btw.)

**Comment by slhenry** [comment]
I think we will need for each section a "Last updated" date.

**Comment by yatil** [comment]
@slhenry What do you mean with “each section”? Each policy has its own updated date.

**Comment by dboudreau** [comment]
I think well chosen icons with relevant alt text used in the context of a much simpler table would bot cause too many concerns. Removing the flag dynamically after a few weeks/months could magically disappear at some point, so there's no maintenance issues either. So:

- +1 to icon
- +1 to 3 month
- +1 to dynamically generating icons so there's no maintenance

**Comment by AndrewArch** [comment]
@sharronrush nice, but not our job to be archivists 
>Archived history of laws that have been superseded seems unnecessary to me, but if others think important, could create a "History" section in supporting material outside of the table.

**Comment by yatil** [comment]
@AndrewArch Yes, the question is how we approach that, we might need a change log so people at least have some way to know if something changed. I leave that to MaryJo and others :-)

**Comment by slhenry** [comment]
Discussion in [10 Feb telecon](https://www.w3.org/2017/02/10-eo-minutes.html#item06)

**Comment by maryjom** [comment]
In addition, we removed the last updated date column from the table itself as it was confusing to many.
As for updated icons, we documented our solution to the timing of indicators to show what has been updated in the "3 months" and the "6 months". See Issue #42 for tracking the icon solution.

As such, this can be closed.
