### ISSUE TITLE
Country in left nav and table are pulling country names from the file name, not the actual name

### ISSUE THREAD

**Issue by maryjom** [w3c/wai-policies-prototype#80]
The capitalization of countries with two word names is not correct. Also, if the country file name has an underscore in it, that underscore is showing up in the left nav menu and in the table (e.g. United_kingdom which should be United Kingdom).  These pieces of information should instead come from the English country name contained inside of the file which has the grammatically correct name for the country.

**Comment by iamjolly** [comment]
This is still pulling from the file name (for now) but I have this displaying properly capitalized names without underscores. We will want to pull this from the [en] country name in the file as you suggested, or from the country name in the language of the page (future logic to be built).

For now, the policy/country file name should be all lowercase and use spaces instead of underscores (e.g. united states.md, new zealand.md).

**Comment by iamjolly** [comment]
This was fixed, courteously, by @yatil with his [commit on 12 April](https://github.com/w3c/wai-policies-prototype/commit/5b72097e0b3527e87a84f1731be7c91e2a21cf2a). Thank you, Eric!
